[build]
  command = "cd my-workspace && npx nx build my-workspace"
  publish = "my-workspace/dist/apps/my-workspace"

[functions]
  directory = "my-workspace/.netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
