[build]
  command = "npm --prefix my-workspace run build"
  publish = "my-workspace/dist"

[functions]
  directory = "my-workspace/.netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
