[build]
  command = "cd my-workspace && npx nx run-many -t build"
  publish = "my-workspace/dist"

[functions]
  directory = "my-workspace/.netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
